spring:
  profiles:
    active: @env@
  datasource:
    url: jdbc:mysql://localhost:3306/
    password: root
    username: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8090
  servlet:
    context-path: /share


